name: Build Wheels

on:
  pull_request:
    branches:
      - main

jobs:

  build-wheels-windows:
    name: Build wheels on ${{ matrix.os }} ( ${{ matrix.platform }} )
    strategy:
      matrix:
        os:
        - windows-2019
        platform:
        #- Win32
        - x64
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build C Library
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install cmake
        cmake -S google_crc32c -B build -G "Visual Studio 16 2019" -A ${{ matrix.platform }} -DCRC32C_BUILD_BENCHMARKS=no -DCRC32C_BUILD_TESTS=no -DBUILD_SHARED_LIBS=yes -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=yes -DCRC32C_USE_GLOG=0
        cmake --build build --verbose --config Release
        cmake --install build --verbose --config Release --prefix ${{ github.workspace }}/usr
        copy ${{ github.workspace }}/usr/bin/crc32c.dll .

    - name: Build Wheels
      uses: pypa/cibuildwheel@v2.1.1
      env:
        CIBW_ENVIRONMENT: CRC32C_INSTALL_PREFIX=${{ github.workspace }}/usr
        CIBW_BUILD_VERBOSITY: 1
        CIBW_TEST_REQUIRES: pytest
        CIBW_TEST_COMMAND: py.test -v {project}/tests

    - uses: actions/upload-artifact@v2
      with:
        name: python-package-distributions
        path: ./wheelhouse/google_crc32c*.whl
